
<section class="container">
    <h1>Espace candidat</h1>
    
    <form method="post" action="/candidat/login/login">
        <label for="email">email</label>
        <input type="email" name="email">
        <br>
        <label for="password">Mot de passe</label>
        <input type="password" name="password">
        <br><br>
        <button type="submit">Connexion</button>
    </form>
</section>