<section class="container">
    <div class="row">
        <div class="col-sm-4">
        </div>
        
        <div class="col-sm-8">
            <h1 class="center">Connexion</h1>
            <br>
            <form method="post" action="/utilisateur/login/login">
                <!-- email -->
                <div class="row">
                    <div class="col-sm-3">
                        <label for="email">Adresse e-mail</label>
                    </div>
                    <div class="col-sm-9">
                        <input class="form-control" placeholder="vous@domaine.com" type="email" name="email">
                    </div>
                </div>
                <br>
                <!-- password -->
                <div class="row">
                    <div class="col-sm-3">
                        <label for="password">Mot de passe</label>
                    </div>
                    <div class="col-sm-9">
                        <input class="form-control" type="password" name="password">
                    </div>
                </div>
                <br>
                <input type="checkbox"> <label>Se souvenir de moi</label>
                <br>
                <div class="center">
                    <button class="btn btn-primary" type="submit">Connexion</button>
                </div>
            </form>
            <br><br>
            <div class="row">
                <div class="col-sm-1"></div>
    
                <div class="col-sm-2">
                    <i class="fa fa-linkedin fa-2x" aria-hidden="true"></i>
                </div>
                <div class="col-sm-2">
                    <i class="fa fa-google-plus fa-2x" aria-hidden="true"></i>
                </div>
                <div class="col-sm-2">
                    <i class="fa fa-twitter fa-2x" aria-hidden="true"></i>
                </div>
                <div class="col-sm-2">
                    <i class="fa fa-github fa-2x" aria-hidden="true"></i>
                </div>
                <div class="col-sm-2">
                    <i class="fa fa-facebook fa-2x" aria-hidden="true"></i>
                </div>
                <div class="col-sm-1"></div>
            </div>
            <br>
            <div class="center">
                Pas encore inscrit ? <a href="/utilisateur/register/index">S'inscrire</a>
            </div>
            


        </div>
    </div>
</section>