<section class="container">
    <div class="row">
        <div class="col-sm-2">
            <span class="user-name">
                <?php echo $user->getPrenom(); ?>
                <?php echo $user->getNom(); ?>
            </span><br><br>

            <img class= "profileIMG" src= "<?php echo $user->getPhoto(); ?>" ><br><br>


        Depuis le  <?php echo date("d/m/Y", $user->getInscription()); ?> <br><br>

            <ul class="list-group">
                <li class="list-group-item"><?php echo $user->getVisites();?>  Visites</li>
                <li class="list-group-item">4 favoris</li>
                <li class="list-group-item">20 matches</li>
            </ul>
        </div>
        <div class="col-sm-10">
            <nav class="navbar">
            <div class="container-fluid">
              <ul class="nav navbar-nav">
                <li class="active"><a href="/utilisateur/profile/edit">Mon profil <span class="sr-only">(current)</span></a></li>
                <li><a href="#">Mes matches</a></li>
                <li><a href="#">Mes favoris</a></li>
                <li><a href="/utilisateur/profile/index">Mon Info</a></li>
              </ul>
            </div>
          </nav>

            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h3 class="panel-title">Informations personnelles</h3>
                </div>
                <div class="panel-body">
                    <form>
                        <div class="row">
                            <div class="col-sm-2">
                                <label for="nom">Nom</label>
                            </div>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" name="nom" placeholder="Nom">
                            </div>
                        </div>

                        <div class="row" style="margin-top: 0.5em;">
                            <div class="col-sm-2">
                                <label for="prenom">Prenom</label>
                            </div>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" name="prenom" placeholder="Prenom">
                            </div>
                        </div>

                        <div class="row" style="margin-top: 0.5em;">
                            <div class="col-sm-2">
                                <label for="date_naissance">Date de naissance</label>
                            </div>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" name="date_naissance" placeholder="Date de naissance">
                            </div>
                        </div>

                        <div class="row" style="margin-top: 0.5em;">
                            <div class="col-sm-2">
                                <label for="telephone">Téléphone</label>
                            </div>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" name="telephone" placeholder="Téléphone">
                            </div>
                        </div>

                        <div class="row" style="margin-top: 0.5em;">
                            <div class="col-sm-2">
                                <label for="adresse">Adresse</label>
                            </div>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" name="adresse" placeholder="Adresse">
                            </div>
                        </div>

                        <div class="row" style="margin-top: 0.5em;">
                            <div class="col-sm-2">
                                <label for="cp">Code postal</label>
                            </div>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" name="cp" placeholder="Code postal">
                            </div>
                        </div>


                        <div class="right">
                            <br><button type="submit" class="btn btn-primary">Valider</button>
                        </div>
                    </form>
                </div>
            </div>

            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Description</h3>
                </div>
                <div class="panel-body">
                    <form>
                        <textarea class="form-control" style="width: 100%; height: 20em;"></textarea>
                        <div class="right">
                            <br><button type="submit" class="btn btn-primary">Valider</button>
                        </div>
                    </form>
                </div>
            </div>

            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Profil recherché</h3>
                </div>
                <div class="panel-body">
                    <form>

                        <select>
                            <option>Type de contrat</option>
                        </select>

                        <select>
                            <option>Poste</option>
                        </select>

                        <select>
                            <option>Lieux</option>
                        </select>
                        &nbsp;&nbsp;
                        <label>Salaire minimum</label>&nbsp;&nbsp;
                        <input id="ex1" data-slider-id='ex1Slider' type="text" data-slider-min="800" data-slider-max="6000" data-slider-step="100" data-slider-value="2200">
                        <script type="text/javascript">
                            $('#ex1').slider({
                                formatter: function(value) {
                                    return 'Current value: ' + value;
                                }
                            });
                        </script>

                        <br> <br>
                        <div class="skills">
                        <input type="checkbox"> <label>Html</label>
                        <input type="checkbox"> <label>Php</label>
                        <input type="checkbox"> <label>Java</label>
                        <input type="checkbox"> <label>Php</label>
                        <br>

                        <input type="checkbox"> <label>Ruby</label>
                        <input type="checkbox"> <label>C</label>
                        <input type="checkbox"> <label>C#</label>
                        <input type="checkbox"> <label>C++</label>
                        <br>
                        <input type="checkbox"> <label>Python</label>
                        <input type="checkbox"> <label>Javascript</label>
                        <input type="checkbox"> <label>Illustrator</label>
                        <input type="checkbox"> <label>Photoshop</label>

                        </div>
                        <div class="right">
                            <br><button type="submit" class="btn btn-primary">Valider</button>
                        </div>
                    </form>
                </div>
            </div>

            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Creer votre annonce</h3>
                </div>
                <div class="panel-body">
                    <form>
                        <input class="form-control" type="text" placeholder="Intitulé du poste"><br>


                        <select>
                            <option>Type de contrat</option>
                        </select>

                        <select>
                            <option>Poste</option>
                        </select>

                        <select>
                            <option>Lieux</option>
                        </select>
                        &nbsp;&nbsp;
                        <label>Salaire minimum</label>&nbsp;&nbsp;
                        <input id="ex2" data-slider-id='ex1Slider' type="text" data-slider-min="800" data-slider-max="6000" data-slider-step="100" data-slider-value="2200">
                        <script type="text/javascript">
                            $('#ex2').slider({
                                formatter: function(value) {
                                    return 'Current value: ' + value;
                                }
                            });
                        </script>

                        <br> <br>
                        <div class="skills well">
                            <strong>Compétences</strong><br><br>
                            <input type="checkbox"> <label>Html</label>
                            <input type="checkbox"> <label>Php</label>
                            <input type="checkbox"> <label>Java</label>
                            <input type="checkbox"> <label>Php</label>
                            <br>

                            <input type="checkbox"> <label>Ruby</label>
                            <input type="checkbox"> <label>C</label>
                            <input type="checkbox"> <label>C#</label>
                            <input type="checkbox"> <label>C++</label>
                            <br>
                            <input type="checkbox"> <label>Python</label>
                            <input type="checkbox"> <label>Javascript</label>
                            <input type="checkbox"> <label>Illustrator</label>
                            <input type="checkbox"> <label>Photoshop</label>
                        </div>

                        <strong>Détails du poste</strong>
                        <textarea class="form-control"></textarea>

                        <div class="right">
                            <br><button type="submit" class="btn btn-primary">Valider</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

</section>
