<?php echo $this->doctype(); ?>
<html lang="fr">

<head>
	<title>Adopte un patron</title>
	<meta charset="UTF-8">
	<?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

	<!-- Le styles -->
	<?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                    ->prependStylesheet($this->basePath() . '/css/main.css')
					->prependStylesheet($this->basePath() . '/css/font-awesome.min.css')
					->prependStylesheet($this->basePath() . '/css/bootstrap-slider.min.css')
					->prependStylesheet($this->basePath() . '/css/bootflat.min.css')
					->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

	<!-- Scripts -->
	<?php echo $this->headScript()
		->prependFile($this->basePath() . '/js/bootstrap-slider.min.js')
        ->prependFile($this->basePath() . '/js/bootstrap.min.js')
        ->prependFile($this->basePath() . '/js/jquery-3.1.1.min.js')
        ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
    ; ?>
</head>

<body>
	<header>
		<nav class="navbar navbar-inverse navbar-fixed-top navbarmain">
			<div class="container-fluid">
				<ul class="nav navbar-nav navbar-left">
					<li><a href="/"><span class="glyphicon glyphicon-briefcase" aria-hidden="true"></span> AdopteUnPatron</a></li>
				</ul>
				<!--
				<form class="navbar-form navbar-left inline-form">
					<div class="form-group">
						<input type="search" class="input-sm form-control" placeholder="Rechercher une offre">
						<button type="submit" class="btn btn-primary btn-sm"><span class="glyphicon glyphicon-eye-open"></span> Chercher</button>
					</div>
				</form>
				-->
				<ul class="nav navbar-nav navbar-right">
					<li class="active">
						<li><a href="/404">Nos Offres</a></li>
						<li><a href="#comment_ca_marche">Comment ça marche ?</a></li>
						<li><a href="#evenements">Evènements</a></li>
						<li><a href="/utilisateur/login/index">Connexion</a></li>
						<li><a href="/utilisateur/register/index">Inscription</a></li>
				</ul>
			</div>
		</nav>
	</header>

	<main>
		<br><br><br><br><br><br>
		<?php echo $this->content; ?>
        <br><br><br>
	</main>
    
	<footer>
		<a href="#">Aide</a> -
		<a href="#">C.G.U</a> -
		<a href="#">Mentions légales</a> -
		<a href="#">Nous contacter</a>
		<div class="socials">
			<i class="fa fa-linkedin fa-2x" aria-hidden="true"></i>
			<i class="fa fa-google-plus fa-2x" aria-hidden="true"></i>
			<i class="fa fa-twitter fa-2x" aria-hidden="true"></i>
			<i class="fa fa-github fa-2x" aria-hidden="true"></i>
			<i class="fa fa-facebook fa-2x" aria-hidden="true"></i>
		</div>
		<span class="glyphicon glyphicon-briefcase" aria-hidden="true"></span> Adopte ta mère &copy; 2017
	</footer>
	<?php echo $this->inlineScript() ?>
</body>
</html>