<section class="container">
	<div class="jumbotron">
		<div class="container">
			
		
		<h1>Hello, world!</h1>
		<p> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis eget mi nec libero cursus efficitur. Nam eu libero eget tellus finibus tincidunt. Morbi velit elit, ullamcorper ut elit eu, pellentesque pellentesque dui. Maecenas vitae faucibus tortor. Fusce diam urna, lobortis et luctus nec, rhoncus ut nisl. Donec malesuada ornare neque in rhoncus. Vestibulum iaculis eleifend diam ut placerat. Nullam vitae ipsum gravida, iaculis lorem non, maximus sapien. Etiam bibendum luctus augue sed hendrerit. Suspendisse tellus eros, porta sollicitudin maximus nec, dignissim vel nisl. Ut et turpis a velit efficitur euismod dignissim ut justo. In accumsan quam sit amet facilisis convallis.
<br><br>
Nunc fermentum tellus eget enim mattis feugiat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. In dignissim justo eu nisi egestas finibus. Nulla facilisi. Nam varius luctus gravida. Aliquam suscipit diam turpis, sed commodo nisi varius ut. Quisque a leo euismod, maximus sem ultrices, blandit velit. Pellentesque euismod mollis nisl. Cras quis odio tincidunt, tempor nibh id, rutrum neque. Donec vel scelerisque dui. Nullam eget neque velit. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.
<br><br>
Aenean pretium accumsan iaculis. In hac habitasse platea dictumst. Nullam sollicitudin gravida dolor at rutrum. Praesent ut porttitor lectus. Duis tincidunt magna ante, sit amet ultrices dolor rutrum sed. Etiam sed est at nisi sollicitudin malesuada. Suspendisse vehicula aliquet mauris hendrerit malesuada. Donec tempus erat vitae neque varius, sit amet feugiat purus molestie. Ut eget odio in eros auctor tincidunt. Duis vel semper lectus, eget faucibus tellus. Donec laoreet ante nec posuere varius. Suspendisse vitae vestibulum justo, in gravida ipsum. </p>
		<p>
			<a class="btn btn-primary btn-lg" href="#" role="button">Je m'inscris</a>
			<br><br>
		</p>
		</div>
	</div>

</section>

<section class="container">
	<h2 class="bandeau">Comment ça marche</h2>
	<div class="row">
		<div class="col-sm-4">
			<div class="thumbnail">
				<img src="..." alt="...">
				<div class="caption">
					<h3>Thumbnail label</h3>
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas massa urna, dictum ut eleifend et, sagittis eu nisi. Fusce a turpis fermentum neque posuere ultricies ut eu felis. Donec tempor eget ex sed porta. Nullam volutpat ante tortor, a sodales leo luctus et. Cras eu nunc varius, rutrum dui ut, facilisis eros. Morbi ac metus porta, mattis nisl ut, varius tortor.</p>
				</div>
			</div>
		</div>

		<div class="col-sm-4">
			<div class="thumbnail">
				<img src="..." alt="...">
				<div class="caption">
					<h3>Thumbnail label</h3>
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas massa urna, dictum ut eleifend et, sagittis eu nisi. Fusce a turpis fermentum neque posuere ultricies ut eu felis. Donec tempor eget ex sed porta. Nullam volutpat ante tortor, a sodales leo luctus et. Cras eu nunc varius, rutrum dui ut, facilisis eros. Morbi ac metus porta, mattis nisl ut, varius tortor.</p>
				</div>
			</div>
		</div>

		<div class="col-sm-4">
			<div class="thumbnail">
				<img src="..." alt="...">
				<div class="caption">
					<h3>Thumbnail label</h3>
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas massa urna, dictum ut eleifend et, sagittis eu nisi. Fusce a turpis fermentum neque posuere ultricies ut eu felis. Donec tempor eget ex sed porta. Nullam volutpat ante tortor, a sodales leo luctus et. Cras eu nunc varius, rutrum dui ut, facilisis eros. Morbi ac metus porta, mattis nisl ut, varius tortor.</p>
				</div>
			</div>
		</div>
	</div>
</section>
<section class="container">
	<h2 class="bandeau">Evènements</h2>
	<div class="row tableau">
		<div class="col-sm-6 big-col">uytuytuytt
			<br>kjhkjh</div>
		<div class="col-sm-6">
			<div class="row">
				<div class="col-sm-6">ghjj</div>
				<div class="col-sm-6">vghvg</div>
			</div>
			<div class="row">
				<div class="col-sm-6">hghg</div>
				<div class="col-sm-6">xdfdx</div>
			</div>
		</div>
	</div>
</section>
<section>
	<h2 class="bandeau">Les entreprises qui recrutent</h2>

	<div class="logos">
		<div><img src="http://placehold.it/64x64" class=" img-rounded"></div>
		<div><img src="http://placehold.it/64x64" class=" img-rounded"></div>
		<div><img src="http://placehold.it/64x64" class=" img-rounded"></div>
		<div><img src="http://placehold.it/64x64" class=" img-rounded"></div>
		<div><img src="http://placehold.it/64x64" class=" img-rounded"></div>
		<div><img src="http://placehold.it/64x64" class=" img-rounded"></div>
		<div><img src="http://placehold.it/64x64" class=" img-rounded"></div>

	</div>
</section>