<section class="container">
		<div class="jumbotron">
			<h1>Hello, world!</h1>
			<p>...</p>
			<p><a class="btn btn-primary btn-lg" href="#" role="button">Je m'inscris</a></p>
		</div>

	</section>

	<section class="container">
		<h2 class="bandeau">Comment ça marche</h2>
		<div class="row">
			<div class="col-sm-4">
				<div class="thumbnail">
					<img src="..." alt="...">
					<div class="caption">
						<h3>Thumbnail label</h3>
						<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas massa urna, dictum ut eleifend et, sagittis eu nisi. Fusce a turpis fermentum neque posuere ultricies ut eu felis. Donec tempor eget ex sed porta. Nullam volutpat ante tortor, a sodales leo luctus et. Cras eu nunc varius, rutrum dui ut, facilisis eros. Morbi ac metus porta, mattis nisl ut, varius tortor.</p>

					</div>
				</div>
			</div>

			<div class="col-sm-4">
				<div class="thumbnail">
					<img src="..." alt="...">
					<div class="caption">
						<h3>Thumbnail label</h3>
						<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas massa urna, dictum ut eleifend et, sagittis eu nisi. Fusce a turpis fermentum neque posuere ultricies ut eu felis. Donec tempor eget ex sed porta. Nullam volutpat ante tortor, a sodales leo luctus et. Cras eu nunc varius, rutrum dui ut, facilisis eros. Morbi ac metus porta, mattis nisl ut, varius tortor.</p>

					</div>
				</div>
			</div>

			<div class="col-sm-4">
				<div class="thumbnail">
					<img src="..." alt="...">
					<div class="caption">
						<h3>Thumbnail label</h3>
						<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas massa urna, dictum ut eleifend et, sagittis eu nisi. Fusce a turpis fermentum neque posuere ultricies ut eu felis. Donec tempor eget ex sed porta. Nullam volutpat ante tortor, a sodales leo luctus et. Cras eu nunc varius, rutrum dui ut, facilisis eros. Morbi ac metus porta, mattis nisl ut, varius tortor.</p>

					</div>
				</div>
			</div>
		</div>
	</section>
	<section class="container">
		<h2 class="bandeau">Evènements</h2>
		<div class="row tableau">
			<div class="col-sm-6 big-col">uytuytuytt
				<br>kjhkjh</div>
			<div class="col-sm-6">
				<div class="row">
					<div class="col-sm-6">ghjj</div>
					<div class="col-sm-6">vghvg</div>
				</div>
				<div class="row">
					<div class="col-sm-6">hghg</div>
					<div class="col-sm-6">xdfdx</div>
				</div>
			</div>
		</div>
	</section>
    <section>
        <h2 class="bandeau">Les entreprises qui recrutent</h2>
        
        <div class="logos">
			<div><img src="http://placehold.it/64x64" class=" img-rounded"></div>
			<div><img src="http://placehold.it/64x64" class=" img-rounded"></div>
			<div><img src="http://placehold.it/64x64" class=" img-rounded"></div>
			<div><img src="http://placehold.it/64x64" class=" img-rounded"></div>
			<div><img src="http://placehold.it/64x64" class=" img-rounded"></div>
			<div><img src="http://placehold.it/64x64" class=" img-rounded"></div>
			<div><img src="http://placehold.it/64x64" class=" img-rounded"></div>

		</div>
    </section>